







Cave.create title: "Cave of the Ghost – Cainama National Park, Venezuela", photo: "http://cdn.list25.com/wp-content/uploads/2013/02/Slide2523.jpg", content: "Also known as ‘La Cueva del Fantasma,’ this is an interesting cave located in southern Venezuela. Situated in one of the most biologically rich and geologically ancient parts of the world in the Aprada tepui, it is just barely large enough to contain two helicopters. However, experts believed that this is not actually a cave but a collapsed steep gorge."
Cave.create title: "Cave of the Swallows – Aquismon, Mexico", photo: "http://cdn.list25.com/wp-content/uploads/2013/02/Slide2423.jpg", content: "An open airpit cave situated at the Municipality of Aquismon in Mexico, it has freefall drop of 333 m from the floor of the cave to the lowest side of the opening, with 370 m drop from the highest side. The 2nd deepest pit in Mexico and the 11th in the world, a skyscraper like the NYC Chrysler Building could easily fit. The cave has low temperatures with thick vegetation at the mouth and rains can cause waterfalls to cascade into its opening. Aside from the layers of debris and guano, you can also find a sinkhole in a fault of the lower Cretaceous limestone, which can go down further to 512 m."
Cave.create title: "Fingal Cave – Staffa, Scotland", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide2323.jpg", content: "A sea cave on the uninhabited island of Staffa in Scotland, it was formed entirely from hexagonally-jointed basalt columns within a Paleocene lava flow. It is well-known for its naturally arched roof, which produces eerie sounds made by the echoes of the waves to give the atmosphere of a natural cathedral."
Cave.create title: "Glowworm Cave – Waitomo, New Zealand", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide2223.jpg", content: "A cave at Waitomo on the north island of New Zealand, it is known for the population of glowworms that are around the size of an average mosquito. It is part of the Waitomo Cave system along with the Ruakuri Cave and the Aranui Cave. Unique only to New Zealand, this is a must-see for any traveler who can enjoy a boat ride amidst thousands of glowworms illuminating the cave and be a part of over 120 years of cultural and natural history."
Cave.create title: "Cave of Crystals – Chihuahua, Mexico", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide2125.jpg", content: "This was just recently discovered in 2000 when scientists discovered the chasm below after drilling an aquifer and pumping out tens of thousands of gallons of water. A cave that is connected to the Naica Mine in Chihuahua, Mexico, its crystal formations are mind bogglingly large and measure over 30 feet in height and 4 feet in diameter. Formed due to the water-source that is rich in calcium sulphate, it was heated by an infusion of magma making the cave extremely hot and people can only endure ten minutes of exposure with proper protection. This is also the reason why most parts of the cave are unexplored."
Cave.create title: "Lascaux Caves – Motignac, France", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide2022.jpg", content: "The location of some complex caves in southwestern France, it is more famous for its Paleolithic cave paintings, which were discovered by a teenager in the 1940s. The Paleolithic art, which is estimated to be 17,300 years old consists of images of large animals known to exist in the area due to fossil evidence. Listed as a UNESCO World Heritage Site in 1979, it was opened in 1948 but was closed down to the public until 1963 to preserve the art. The rooms in the cave that you can explore include the Chamber of Felines, the Hall of the Bulls, the Apse, the Nave, the Shaft, and the Passageway."
Cave.create title: "Ice Cavern – Skattafel, Iceland", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide1922.jpg", content: "The Kverkfjöll ice cave, located in a frozen lagoon in Skattafel, Iceland, is considered one of the most famous glacier caves in the world. Formed by the hot water from a volcanic spring below Vatnajökull glacier, it was discovered during an expedition in the 1980s."
Cave.create title: "Blue Grotto – Capri, Italy", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide1822.jpg", content: "A famous sea cave on the coast of the island of Capri in Italy, the sunlight that passes through the underwater cavity and shines through the seawater creates a blue reflection that illuminates the cave."
Cave.create title: "The Reed Flute Cave – Guangxi, China", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide1722.jpg", content: "A landmark and a tourist attraction outside the city of Gullin in Guangxi, China, its name was derived from the reeds growing inside the cave that are ideal for flute making. It offers magnificent rock and mineral formations, stone pillars, and carbon deposits. Illuminated by different colored lights, it has been one of Gulin’s most interesting tourists’ attractions for the past 1,200 years. Rediscovered in 1940s by a group of refugees, this 180 years old cave has more than 70 inscriptions written in ink that date as far as 792 AD to the Tang Dynasty."
Cave.create title: "Fantastic Cave Pit – Georgia, USA", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide1622.jpg", content: "Located in Ellison Caves, east of Lafayette, Georgia, the Fantastic cave is 586 ft deep. Known as the deepest cave in the United States, it is big enough to hold the Washington Monument."
Cave.create title: "Eisriesenwelt Ice Caves – Werfern, Austria", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide1522.jpg", content: "Eisriesenwelt, the German word for “World of the Ice Giants,” is made from natural limestone ice, which is located in Werfen, Austria. Found inside the Hochkogel Mountain, a Tennengebirge section of the Alps, it is considered the ‘largest ice cave in the world.’ Extending more than 42 km, it draws about 200,000 tourists each year due to the ice formations of the cave, which were formed by thawing snow that drained into the cave and froze during winter. During the chilly winter, the winds blow into the cave and freezes the snow inside; while in summer, the cool wind from inside the cave prevents it from melting."
Cave.create title: "Majlis al Jinn Cave – Muscat, Oman", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide1422.jpg", content: "This cave is located in the Selma Plateau, 1,380 m above sea level in the Sultanate of Oman. Formed in fossilliferous carbonate rocks, it is the 9th largest cave chamber in the world. A single chamber alone measures about 310 m by 225 m with a free-standing roof about 40 m thick. The cave has a volume of 4,000,000 cubic meters, while its floor area is about 58,000 square meters. Its deepest part is about 178 m below the top of the highest entrance."
Cave.create title: "Puerto Princesa Underground River – Palawan, Philippines", photo: "http://cdn2.list25.com/wp-content/uploads/2013/02/Slide1323.jpg", content: "A national park since 1971, the Puerto Princesa Subterranean River National Park is located in Palawan, Philippines. Also known as the St. Paul Underground River, it is a part of the Saint Paul Mountain Range. Aside from the underground river where visitors can explore the cave in a boat, it was also discovered in 2010 that the underground river has a second floor, indicating the presence of small waterfalls inside the cave. It is composed of a huge 300-m cave dome; unbelievable rock formations, and an underground river."
Cave.create title: "Onondaga Cave – Missouri, USA", photo: "http://cdn2.list25.com/wp-content/uploads/2013/02/Slide1225.jpg", content: "This cave in Leasburg belongs to Missouri National Park, which was established in 1982. Although it was first settled by people in the 1850s, it has a history of land disputes and vandalism. It is now secured as a protected national park where cave tours, swimming, fishing, picnicking and hiking are being offered at the visitor’s center, which also has a nature museum. The Onondaga Cave boasts of towering stalagmite, dripping stalactites and other active flowstones."
Cave.create title: "Deer Cave – Borneo, Malaysia", photo: "http://cdn2.list25.com/wp-content/uploads/2013/02/Slide1128.jpg", content: "Located near Miri, Sarawak in Malaysian Borneo, it is a cave attraction that is part of the Gunung Mulu National Park. Also known by the locals as ‘Gua Payau’ or ‘Gua Rusa,’ it received its name from the deer that came to lick its salt-bearing rocks and used it as their shelter. First discovered in 1961 by G.E. Wilford, it was further surveyed in 1978 to determine its measurements of 174 m wide and 122m high, while the main entrance measured at 146 m."
Cave.create title: "Škocjan Caves – Trieste, Slovenia", photo: "http://cdn.list25.com/wp-content/uploads/2013/02/Slide1022.jpg", content: "A protected cave system in Slovenia, the cave is just 2 miles long but attracts year-round tourists and visitors. It consists of the Reka River, which goes underground for an additional 21 miles and represents one of the longest ‘karst’ underground wetlands in Europe. It became a UNESCO World Heritage Site in 1986 and was lauded by the scientific community as one of Earth’s natural treasures."
Cave.create title: "Barton Creek Cave – Cayo, Belize", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide922.jpg", content: "A natural cave in Belize near San Ignacio in the district Cayo, it is not only a popular tourist destination but an archaeological site as well. A single-passageway resurging stream with 6,400 meters of passages, there is an indication that there can be an additional 6 km of passageways as shown by the dry traces at sinking streams. An important archaeological site, there was evidence that the first kilometer of the cave passageway was used by Mayans due to a number of pottery shards that have been discovered dating as far back 200 AD along with the remains of 28 humans."
Cave.create title: "Phong Nha Cave – Minh Hoa, Vietnam", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide822.jpg", content: "The Phong Nha Cave, which is a part of the UNESCO World Heritage Site in Phong Nha-Ke Bang National Park, is located in the Minh Hoa districts in north-central Vietnam, about 500 km south of Hanoi. The national park was created to protect its over 300 caves and grottoes, aside from the ecosystem and the limestone forest of the Annamite Range. Out of the 300 Phong Nha caves, only 20 of those have been surveyed by scientists. With a total length of 126 km, it held several records including the longest underground river and the largest caverns and passageways before the discovery of Son Doong Cave."
Cave.create title: "Fantasy Cave – Dannervirke, New Zealand", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide722.jpg", content: "Located in Dannevirke, New Zealand, the Fantasy cave has developed into a year-round exhibit for the locals and tourists alike. Entirely constructed and operated by volunteers, the displays are constantly changed and replaced."
Cave.create title: "Dongzhong Cave – Guizhou, China", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide622.jpg", content: "Literally means “in cave” in Chinese, this is not just an ordinary cave as actually houses a school! Situated in Ziyun County in the province of Guizhou in China, the enourmous cave opened as a school in 1984 with 186 students and 8 teachers. Carved out of the mountain by wind, water, seismic shifts and other natural forces for thousands of years, it now houses rooms, small buildings, and recreational areas for the students."





Place.create title: "Tunnel of Love, Ukraine", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-8.jpg", content: "Tunnel of Love is a beautiful spot in Klevan, Ukraine. A three kilometer railway section leads to the fibreboard factory.

The train goes three times a day and delivers wood to the factory. However, the trees make a green corridor, which attracts many couples, as well as photographers for its eye catching avenue.

It is said that if you and your beloved come to the Tunnel of Love and sincerely make a wish, it will come true. This might be a new romantic place to discover."
Place.create title: "Tulip Fields in Netherlands", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-2.jpg", content: "The weather in Holland is suited to tulip growing, with cool springs just as they begin to bloom. The soil in the polders is always being drained, making it perfect for tulip bulbs that like well-drained but moist soils. There are so many types of tulip varieties, that the Dutch Horticultural society has grouped them into several groups, with differing species within those groups. From mid-March to the end of May the tulips transform large parts of Holland into a colorful patchwork. So when you go to Holland in April to see the tulips bloom, no matter where you look, the fields will be different and no doubt gorgeously colorful."
Place.create title: "Salar de Uyuni
: One of the World’s Largest Mirrors, Bolivia", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-13-2.jpg", content: ""
Place.create title: "Hitachi Seaside Park, Japan", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-23.jpg", content: ""
Place.create title: "Mendenhall Ice Caves, Juneau, Alaska", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-1-1.jpg", content: ""
Place.create title: "Red Beach, Panjin, China", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-24-2.jpg", content: ""
Place.create title: "Bamboo Forest, Japan", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-3-1.jpg", content: ""
Place.create title: "Street in Bonn, Germany", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-6.jpg", content: ""
Place.create title: "Wisteria Flower Tunnel in Japan", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-7-1.jpg", content: ""
Place.create title: "Black Forest, Germany", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-9.jpg", content: ""
Place.create title: "Fields of Tea, China", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-11.jpg", content: ""
Place.create title: "Tianzi Mountains, China", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-12-1.jpg", content: ""
Place.create title: "Shibazakura Flowers, Takinoue Park, Japan", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-25-2.jpg", content: ""
Place.create title: "Antelope Canyon, USA", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-15-2.jpg", content: ""
Place.create title: "Lake Hillier, Australia", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-16.jpg", content: ""
Place.create title: "Lake Retba, Senegal", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-27-1.jpg", content: ""
Place.create title: "Lavender Fields, UK and France", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-10-1.jpg", content: ""
Place.create title: "Canola Flower Fields, China", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-21-1.jpg", content: ""
Place.create title: "Mount Roraima, Venezuela/Brazil/Guyana", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-19-1.jpg", content: ""
Place.create title: "Zhangye Danxia Landform, China", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-27-3.jpg", content: ""
