Island.create(title: "Palawan, Philippines", photo: "http://photos.cntraveler.com/2014/10/10/54381804f2f192ac5aefe691_palawan-philippines-boat-sunset-2048-1536.jpg", content: "This small island—one of the Philippines’ 7,107—shot to the top of our list this year with a recent claim to fame: It’s now home to one of the new seven natural wonders of the world, Puerto Princesa Subterranean River. Pro tip: Palawan's natural wonder is one of the longest underground rivers in the world, traveling five miles through a subterranean cave system. Guided boat tours take visitors down a portion of the waterway, where karsts, natural rock formations created by dissolving limestone, loom in every direction. Getting there: From Manila, it’s an hour-and-15-minute flight to Puerto Princesa, Palawan’s main airport. Alternately, ferries travel between Manila and the island several days a week (about 24 hours each way).")
Island.create(title: "Kiawah Island, South Carolina", photo: "http://photos.cntraveler.com/2014/07/31/53da5b8fdcd5888e145af9dc_golf-resort-kiawah-island-ocean-course.jpg", content: "Though it’s only a short trip from downtown Charleston, this small barrier island on the Atlantic coast can feel like it’s a world away—whether you’re planning a day on the links or a day at the beach. Pro tip: The island is dominated by the Kiawah Island Golf Resort, which is home to 90 holes of golf spread over five courses, many with scenic ocean views. The PGA Championship was held here in 2012. There are also extensive tennis, spa, and dining offerings. Getting there: It’s a 33-mile drive from Charleston International Airport to the island, which is located just off the mainland.")
Island.create(title: "Maui, Hawaii", photo: "http://photos.cntraveler.com/2014/08/07/53e2f9fac2d3f39d3610d4de_maui-road-to-hana-1.jpg", content: "Hawaii’s second-largest island boasts rugged terrain, volcanic beaches, and the towering Mt. Haleakala. It’s the place to be for snorkelers, hikers, and food lovers alike. Pro tip: To catch as much of Maui’s natural beauty as possible, drive the Road to Hana, a 68-mile scenic route featuring awe-inspiring waterfalls and ending at the breathtaking Seven Sacred Pools. Getting there: Many mainland airlines offer direct routes to Maui from airports on the West Coast. Otherwise, it’s about a half-hour flight to the island from Honolulu International Airport.")
Island.create(title: "Kauai, Hawaii", photo: "http://photos.cntraveler.com/2014/08/06/53e2e101c2d3f39d3610721d_na-pali-coast-kauai-hawaii-alamy.jpg", content: "Rain falls on Mount Wai'ale'ale almost 360 days a year, but the weather on the rest of Kauai isn’t nearly so bad. And from rain forests to massive canyons to hidden beaches, it’s the site of incredible biodiversity. Pro tip: Waimea Canyon has been called 'the Grand Canyon of the Pacific,' and the epithet fits. Ten miles across and 3,500 feet deep, it’s been carved out over eons by lava flows and water pouring down from the summit of Wai'ale'ale. Getting there: Some airlines fly directly from West Coast cities to Kauai. If you’re arriving in Honolulu, a trip on a local air carrier takes about half an hour.")
Island.create(title: "Bazaruto Archipelago, Mozambique", photo: "http://photos.cntraveler.com/2014/10/10/543816db00ac583c0af22a71_indian-ocean-bazaruto-archipelag-mozambique-2048-1536.jpg", content: "The entirety of this five-island chain in the Indian Ocean became a national park in 2002, preserving its status as a nearly untouched natural sanctuary. Wildlife abounds here, and the beaches are pristine. Pro tip: A snorkeling or diving expedition is a great way to see Two Mile Reef, a barrier reef that’s home to more than 2,000 species of fish. It’s also home to marine turtles and dugong, an endangered marine mammal similar to manatees. Getting there: From Johannesburg, fly to Vilanculos Airport in Mozambique. From there, many lodges and hotels on Bazaruto offer transfers to the island via helicopter, plane, or boat.")
Island.create(title: "Great Barrier Reef & Whitsunday Islands, Australia", photo: "http://photos.cntraveler.com/2014/08/01/53db2426dcd5888e145e7ee8_5-whitsunday-islands-australia.jpg", content: "The Great Barrier Reef consists of more than 3,000 individual reef systems and hundreds of islands, a living structure so vast that it’s visible from outer space. The 74 islands of the Whitsundays offer some of the best snorkeling and sailing in the world. Pro tip: The waters of Whitehaven Beach are renowned for their swirling bands of colors, a mix of blues, greens, and whites created by changing tides mixing the sand and sea. Getting there: It’s a one-and-a-half-hour domestic flight from Brisbane to the Whitsunday coast.
")
Island.create(title: "Santorini & Cyclades, Greece", photo: "http://photos.cntraveler.com/2014/08/07/53e30759dddaa35c30f6aec0_santorini-cruise-port.jpg", content: "No island group is so shrouded in myth as this chain in the Aegean Sea, site of Apollo’s birthplace on the sacred isle of Delos and the gateway to Hades on uninhabited Keros. Santorini, on the southernmost end of the Cyclades, is a volcanically formed island with dramatic cliffs, ancient ruins, and picturesque towns that’s said to be the inspiration for Plato’s Atlantis. Pro tip: Watch the sun set from Oia, a small village on the southwestern coast made up of whitewashed structures and cave houses built into the cliff side. Getting there: Direct flights to Santorini are available from London and Athens. But if you want to take the scenic route and get the full Cyclades experience, take a ferry from Athens (5 to 8 hours).")
Island.create(title: "St. John, U.S. Virgin Islands", photo: "http://photos.cntraveler.com/2014/08/01/53db25d5dcd5888e145e8930_st-john-protected-parklands-775.jpg", content: "This small isle in the Caribbean Sea hasn’t been overrun by development, thanks to the fact that two-thirds of the landmass is national parkland. It makes an ideal getaway for hikers seeking out jungle trails and snorkelers who'll nose down over the surrounding reefs. Pro tip: With its shallow, turquoise water and soft sand, St. John’s Trunk Bay is often counted among the finest beaches in the world. Explore the diverse marine life with a snorkeling expedition along the Underwater Trail through a teeming coral reef. Getting there: There are no airports on the island, so boat travel is your main option. Ferries depart from two spots on St. Thomas—Red Hook and Charlotte Amalie—and take 20 to 45 minutes to arrive at Cruz Bay in St. John.
")
Island.create(title: "Kangaroo Island, Australia", photo: "http://photos.cntraveler.com/2014/07/31/53da5810dcd5888e145aed1a_southern-ocean-lodge-kangaroo-island-1.jpg", content: "Though Australia’s third-largest island is only ten miles off the coast of Adelaide, its bucolic way of life has remained largely untouched by mainland development. And thanks to its watery isolation, Kangaroo Island has remained predator-free, leaving it home to a huge variety of wildlife: koalas, spiky echidnas, long-nosed bandicoots, sea lions, platypuses, and of course, kangaroos. Pro tip: To experience the island’s natural grandeur, both animal and geological, visit Flinders Chase National Park. Admirals Arch is an otherworldly natural rock formation carved out by the sea, beneath which you can observe colonies of fur seals. Getting there: Regional airlines fly between Adelaide and Kangaroo Island’s Kingscote (30 mins). You can also take a 45-minute ferry ride from Cape Jervis to Penneshaw on the island.")
Island.create(title: "Big Island, Hawaii", photo: "http://photos.cntraveler.com/2014/07/31/53dab67edcd5888e145c7512_helicopter-tour-big-island-falls.jpg", content: "The incredibly varied landscape of Hawaii’s largest island is staggering, from snow-capped peaks and one of the world’s most active volcano (Kilauea) to tropical coves and placid fishing villages. Pro tip: Hawaii Volcanoes National Park is home to three active volcanoes oozing slow-moving lava that you may or may not be able see firsthand. Still, this UNESCO World Heritage Site has more than 140 miles of hiking trails to explore, traveling through rainforests, black lava fields, and up rugged peaks. Getting there: Regular flights travel between Honolulu and the Big Island’s two largest towns, Hilo and Kona.
")
Island.create(title: "Tasmania, Australia", photo: "http://photos.cntraveler.com/2014/08/01/53db24286dec627b14a1d14a_4-tasmania-sleepy-bay-freycinet-peninsula.jpg", content: "Thrill seekers flock to Tasmania, off the coast of South Australia, for its challenging hikes (and rewarding views). Pro tip: Check into the Saffire Freycinet. 'There’s no point in trying to compete with a setting as majestic as the Freycinet Peninsula, with its powder-white beaches and iridescent-blue bays,'' say our readers. Getting there: There are (cheap) flights from Melbourne to Hobart all day on Australia's regional carriers.")
Island.create(title: "Boracay, Philippines", photo: "http://photos.cntraveler.com/2014/10/10/5437f5eff2f192ac5aefe54a_boracay-philippines.jpg", content: "This itty-bitty island (10 square miles) in the Western Philippines is as close to the tropical idyll ideal as you’ll find in the Philippines, with gentle coastlines and transporting sunsets. Add in a thriving nightlife scene, and you have one of the top tourist spots in the region. Pro tip: The aptly named White Beach is Boracay’s main draw, with powdery white sand and shallow azure water ideal for swimming and snorkeling. Getting there: Fly from Manila to Caticlan in Malay; from there, pump boats ferry passengers to White Beach.")
Island.create(title: "Menorca, Spain", photo: "http://photos.cntraveler.com/2014/10/10/54383651f2f192ac5aefe745_menorca-spain-night-ferry-2048-1536.jpg", content: "Menorca wins among the Balearic Islands, with more (and superior) beaches than Ibiza and Mallorca combined. UNESCO has declared it a biosphere reserve to help guard its natural wetlands and rare archeological sites, which has kept tourism low-rise and low-key. Pro tip: Beaches and coast-adjacent restaurants are a no-brainer, but don’t miss the chance to explore Menorca’s enigmatic megaliths—so many, in fact, that the island is home to the greatest concentration of prehistoric monuments in the world. Getting there: For a sea voyage, take a ferry to the island from Barcelona (9 hours). If you’d rather have a shorter journey, flights travel direct to Menorca from many major European cities.")
Island.create(title: "Bermuda", photo: "http://photos.cntraveler.com/2014/07/31/53da8b14dcd5888e145bb49c_1-bermuda-tuckers-town.jpg", content: "Though this small island sits in the North Atlantic, its climate is decidedly subtropical. A British Overseas Territory, Bermuda is a melting pot of British, American, and Caribbean cultures, and offers tons of things to do: snorkeling near pink-sand beaches, golfing, shopping, museum hopping, and more. Pro tip: Bermuda is riddled with watery underground caverns, its most famous being the Crystal and Fantasy Caves. Tours take you on a walkway over eerily clear water, with pale stalactites hanging overhead. One of the site’s first visitors? Mark Twain. Getting there: There are direct flights to Bermuda from eight cities on the East Coast, including New York, Atlanta, and Miami (2 to 3 hours).")
Island.create(title: "Sea Island, Georgia", photo: "http://photos.cntraveler.com/2014/08/07/53e2ff00dddaa35c30f68f48_best-guy-vacations-sea-islands-fishing.jpg", content: "Old Southern charm—and old money—oozes from every pore of this private island just beyond the Georgia marshlands. The area is divided between two high-end resorts, the Sea Island Beach Club and the Cloister, and has played host to famous guests over the years: Calvin Coolidge, Eugene O’Neill, and Bill Clinton among them. Pro tip: The Cloister is as luxurious as resorts come, with a Mediterranean aesthetic, a world-class golf course, horseback riding, a spa, and miles of private beach. Getting there: It’s a 90-minute drive from either Jacksonville, Florida, or Savannah to Sea Island.")
Island.create(title: "Oahu, Hawaii", photo: "http://photos.cntraveler.com/2014/08/01/53db242d6dec627b14a1d171_5-oahu-kailua-bay-hawaii.jpg", content: "The most visited of Hawaii’s islands, Oahu is the seat of the state capital, Honolulu, and also the site of historic Pearl Harbor. The island’s North Shore is legendary for its surfing, and Oahu is one of the most ethnically diverse cities in America. Pro tip: With its views toward Diamond Head and resort surroundings, white-sand Waikiki Beach has one of the most iconic shorelines in the world. Getting there: Hawaii’s main airport in Honolulu is easily reachable from many cities on the mainland.")
Island.create(title: "Bali, Indonesia", photo: "http://photos.cntraveler.com/2014/08/01/53db25b3dcd5888e145e8833_bali-ubud-four-seasons-hotel-775.jpg", content: "There's nothing quite like Bali,' says senior digital editor Laura Dannen Redman. 'It's the kind of place where you'll eat the best fresh fish of your life on the beach with your feet in the sand. You'll watch whole families zoom by on motorbikes, or maybe a monkey will steal your glasses at Uluwatu temple. Every experience is memorable.' Pro tip: Avoid Denpasar, where you fly in, and Kuta, a tourist trap; visit culturally rich Ubud instead, or take a few days to venture north to Munduk in the mountains. Getting there: Many international airlines fly to Bali from hubs in Singapore, Kuala Lumpur, and Hong Kong.")
Island.create(title: "Moorea, French Polynesia", photo: "http://photos.cntraveler.com/2014/07/31/53da8980dcd5888e145bacd6_2-moorea-opunohu-bay.jpg", content: "Due northwest of Tahiti and surrounded by a bright blue lagoon, this volcanically formed island is comprised of verdant mountains jutting up behind white-sand beaches. In the interior, you can explore the ruins of marae—crumbling temples built by ancient Polynesians. Pro tip: Snorkel to your heart’s content at the Lagoonarium de Moorea, a protected part of the lagoon where you can explore a coral reef teeming with sharks, rays and thousands of fish. Getting there: From Papa'ete in Tahiti, boats ferry passengers on the 12-mile journey to Moorea.")
Island.create(title: "Maldives", photo: "http://photos.cntraveler.com/2014/07/31/53da86af6dec627b149f02ce_1-maldives-alifu-dhaalu-atoll-angsana-velavaru-resort.jpg", content: "There’s more ocean than land in the Maldives, a chain of tiny islands and coral atolls far out in the Indian Ocean. Most of the accommodations are on stilts over the water, in high-end luxury resorts (many eco-friendly) that cater to honeymooners and serious divers alike. Pro tip: The Maldives are full of coral reefs that formed around volcanoes in prehistoric times, now sunken to form atolls. The reefs shelter thousands of species of fish, turtles, whales, and dolphins. Many resorts on the islands offer snorkeling excursions for guests looking to explore the underwater landscape. Getting there: Many Asian and European airlines offer indirect flights to Male, the Maldives’ main city, from airports around the world.")
Island.create(title: "Öland, Sweden", photo: "http://photos.cntraveler.com/2014/10/10/5437f2f6f2f192ac5aefe52c_oland-sweden.jpg", content: "A vacation spot for Sweden’s royal family, this island in the Baltic Sea is a popular summer getaway for commoners, too. Here you’ll find pretty beaches, dramatic limestone outcroppings, fairy-tale forests, and hundreds of antique windmills. The whole southern portion of the island is a UNESCO World Heritage Site thanks to its well-preserved farming settlement. Pro tip: Öland is brimming with historical sites, from the prehistoric standing stones at Gettlinge to the medieval ring fort of Eketorp. There’s also Borgholms slott, the ruins of a 12th-century castle ravaged by a 19th-century fire. Getting there: Just off of mainland Sweden, the island is accessible by car or bus via the Öland Bridge.")





# 
#
#
# Cave.create title: "Cave of the Ghost – Cainama National Park, Venezuela", photo: "http://cdn.list25.com/wp-content/uploads/2013/02/Slide2523.jpg", content: "Also known as ‘La Cueva del Fantasma,’ this is an interesting cave located in southern Venezuela. Situated in one of the most biologically rich and geologically ancient parts of the world in the Aprada tepui, it is just barely large enough to contain two helicopters. However, experts believed that this is not actually a cave but a collapsed steep gorge."
# Cave.create title: "Cave of the Swallows – Aquismon, Mexico", photo: "http://cdn.list25.com/wp-content/uploads/2013/02/Slide2423.jpg", content: "An open airpit cave situated at the Municipality of Aquismon in Mexico, it has freefall drop of 333 m from the floor of the cave to the lowest side of the opening, with 370 m drop from the highest side. The 2nd deepest pit in Mexico and the 11th in the world, a skyscraper like the NYC Chrysler Building could easily fit. The cave has low temperatures with thick vegetation at the mouth and rains can cause waterfalls to cascade into its opening. Aside from the layers of debris and guano, you can also find a sinkhole in a fault of the lower Cretaceous limestone, which can go down further to 512 m."
# Cave.create title: "Fingal Cave – Staffa, Scotland", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide2323.jpg", content: "A sea cave on the uninhabited island of Staffa in Scotland, it was formed entirely from hexagonally-jointed basalt columns within a Paleocene lava flow. It is well-known for its naturally arched roof, which produces eerie sounds made by the echoes of the waves to give the atmosphere of a natural cathedral."
# Cave.create title: "Glowworm Cave – Waitomo, New Zealand", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide2223.jpg", content: "A cave at Waitomo on the north island of New Zealand, it is known for the population of glowworms that are around the size of an average mosquito. It is part of the Waitomo Cave system along with the Ruakuri Cave and the Aranui Cave. Unique only to New Zealand, this is a must-see for any traveler who can enjoy a boat ride amidst thousands of glowworms illuminating the cave and be a part of over 120 years of cultural and natural history."
# Cave.create title: "Cave of Crystals – Chihuahua, Mexico", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide2125.jpg", content: "This was just recently discovered in 2000 when scientists discovered the chasm below after drilling an aquifer and pumping out tens of thousands of gallons of water. A cave that is connected to the Naica Mine in Chihuahua, Mexico, its crystal formations are mind bogglingly large and measure over 30 feet in height and 4 feet in diameter. Formed due to the water-source that is rich in calcium sulphate, it was heated by an infusion of magma making the cave extremely hot and people can only endure ten minutes of exposure with proper protection. This is also the reason why most parts of the cave are unexplored."
# Cave.create title: "Lascaux Caves – Motignac, France", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide2022.jpg", content: "The location of some complex caves in southwestern France, it is more famous for its Paleolithic cave paintings, which were discovered by a teenager in the 1940s. The Paleolithic art, which is estimated to be 17,300 years old consists of images of large animals known to exist in the area due to fossil evidence. Listed as a UNESCO World Heritage Site in 1979, it was opened in 1948 but was closed down to the public until 1963 to preserve the art. The rooms in the cave that you can explore include the Chamber of Felines, the Hall of the Bulls, the Apse, the Nave, the Shaft, and the Passageway."
# Cave.create title: "Ice Cavern – Skattafel, Iceland", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide1922.jpg", content: "The Kverkfjöll ice cave, located in a frozen lagoon in Skattafel, Iceland, is considered one of the most famous glacier caves in the world. Formed by the hot water from a volcanic spring below Vatnajökull glacier, it was discovered during an expedition in the 1980s."
# Cave.create title: "Blue Grotto – Capri, Italy", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide1822.jpg", content: "A famous sea cave on the coast of the island of Capri in Italy, the sunlight that passes through the underwater cavity and shines through the seawater creates a blue reflection that illuminates the cave."
# Cave.create title: "The Reed Flute Cave – Guangxi, China", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide1722.jpg", content: "A landmark and a tourist attraction outside the city of Gullin in Guangxi, China, its name was derived from the reeds growing inside the cave that are ideal for flute making. It offers magnificent rock and mineral formations, stone pillars, and carbon deposits. Illuminated by different colored lights, it has been one of Gulin’s most interesting tourists’ attractions for the past 1,200 years. Rediscovered in 1940s by a group of refugees, this 180 years old cave has more than 70 inscriptions written in ink that date as far as 792 AD to the Tang Dynasty."
# Cave.create title: "Fantastic Cave Pit – Georgia, USA", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide1622.jpg", content: "Located in Ellison Caves, east of Lafayette, Georgia, the Fantastic cave is 586 ft deep. Known as the deepest cave in the United States, it is big enough to hold the Washington Monument."
# Cave.create title: "Eisriesenwelt Ice Caves – Werfern, Austria", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide1522.jpg", content: "Eisriesenwelt, the German word for “World of the Ice Giants,” is made from natural limestone ice, which is located in Werfen, Austria. Found inside the Hochkogel Mountain, a Tennengebirge section of the Alps, it is considered the ‘largest ice cave in the world.’ Extending more than 42 km, it draws about 200,000 tourists each year due to the ice formations of the cave, which were formed by thawing snow that drained into the cave and froze during winter. During the chilly winter, the winds blow into the cave and freezes the snow inside; while in summer, the cool wind from inside the cave prevents it from melting."
# Cave.create title: "Majlis al Jinn Cave – Muscat, Oman", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide1422.jpg", content: "This cave is located in the Selma Plateau, 1,380 m above sea level in the Sultanate of Oman. Formed in fossilliferous carbonate rocks, it is the 9th largest cave chamber in the world. A single chamber alone measures about 310 m by 225 m with a free-standing roof about 40 m thick. The cave has a volume of 4,000,000 cubic meters, while its floor area is about 58,000 square meters. Its deepest part is about 178 m below the top of the highest entrance."
# Cave.create title: "Puerto Princesa Underground River – Palawan, Philippines", photo: "http://cdn2.list25.com/wp-content/uploads/2013/02/Slide1323.jpg", content: "A national park since 1971, the Puerto Princesa Subterranean River National Park is located in Palawan, Philippines. Also known as the St. Paul Underground River, it is a part of the Saint Paul Mountain Range. Aside from the underground river where visitors can explore the cave in a boat, it was also discovered in 2010 that the underground river has a second floor, indicating the presence of small waterfalls inside the cave. It is composed of a huge 300-m cave dome; unbelievable rock formations, and an underground river."
# Cave.create title: "Onondaga Cave – Missouri, USA", photo: "http://cdn2.list25.com/wp-content/uploads/2013/02/Slide1225.jpg", content: "This cave in Leasburg belongs to Missouri National Park, which was established in 1982. Although it was first settled by people in the 1850s, it has a history of land disputes and vandalism. It is now secured as a protected national park where cave tours, swimming, fishing, picnicking and hiking are being offered at the visitor’s center, which also has a nature museum. The Onondaga Cave boasts of towering stalagmite, dripping stalactites and other active flowstones."
# Cave.create title: "Deer Cave – Borneo, Malaysia", photo: "http://cdn2.list25.com/wp-content/uploads/2013/02/Slide1128.jpg", content: "Located near Miri, Sarawak in Malaysian Borneo, it is a cave attraction that is part of the Gunung Mulu National Park. Also known by the locals as ‘Gua Payau’ or ‘Gua Rusa,’ it received its name from the deer that came to lick its salt-bearing rocks and used it as their shelter. First discovered in 1961 by G.E. Wilford, it was further surveyed in 1978 to determine its measurements of 174 m wide and 122m high, while the main entrance measured at 146 m."
# Cave.create title: "Škocjan Caves – Trieste, Slovenia", photo: "http://cdn.list25.com/wp-content/uploads/2013/02/Slide1022.jpg", content: "A protected cave system in Slovenia, the cave is just 2 miles long but attracts year-round tourists and visitors. It consists of the Reka River, which goes underground for an additional 21 miles and represents one of the longest ‘karst’ underground wetlands in Europe. It became a UNESCO World Heritage Site in 1986 and was lauded by the scientific community as one of Earth’s natural treasures."
# Cave.create title: "Barton Creek Cave – Cayo, Belize", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide922.jpg", content: "A natural cave in Belize near San Ignacio in the district Cayo, it is not only a popular tourist destination but an archaeological site as well. A single-passageway resurging stream with 6,400 meters of passages, there is an indication that there can be an additional 6 km of passageways as shown by the dry traces at sinking streams. An important archaeological site, there was evidence that the first kilometer of the cave passageway was used by Mayans due to a number of pottery shards that have been discovered dating as far back 200 AD along with the remains of 28 humans."
# Cave.create title: "Phong Nha Cave – Minh Hoa, Vietnam", photo: "http://cdn3.list25.com/wp-content/uploads/2013/02/Slide822.jpg", content: "The Phong Nha Cave, which is a part of the UNESCO World Heritage Site in Phong Nha-Ke Bang National Park, is located in the Minh Hoa districts in north-central Vietnam, about 500 km south of Hanoi. The national park was created to protect its over 300 caves and grottoes, aside from the ecosystem and the limestone forest of the Annamite Range. Out of the 300 Phong Nha caves, only 20 of those have been surveyed by scientists. With a total length of 126 km, it held several records including the longest underground river and the largest caverns and passageways before the discovery of Son Doong Cave."
# Cave.create title: "Fantasy Cave – Dannervirke, New Zealand", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide722.jpg", content: "Located in Dannevirke, New Zealand, the Fantasy cave has developed into a year-round exhibit for the locals and tourists alike. Entirely constructed and operated by volunteers, the displays are constantly changed and replaced."
# Cave.create title: "Dongzhong Cave – Guizhou, China", photo: "http://cdn4.list25.com/wp-content/uploads/2013/02/Slide622.jpg", content: "Literally means “in cave” in Chinese, this is not just an ordinary cave as actually houses a school! Situated in Ziyun County in the province of Guizhou in China, the enourmous cave opened as a school in 1984 with 186 students and 8 teachers. Carved out of the mountain by wind, water, seismic shifts and other natural forces for thousands of years, it now houses rooms, small buildings, and recreational areas for the students."
#
#
#
#
#
# Place.create title: "Tunnel of Love, Ukraine", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-8.jpg", content: "Tunnel of Love is a beautiful spot in Klevan, Ukraine. A three kilometer railway section leads to the fibreboard factory.
#
# The train goes three times a day and delivers wood to the factory. However, the trees make a green corridor, which attracts many couples, as well as photographers for its eye catching avenue.
#
# It is said that if you and your beloved come to the Tunnel of Love and sincerely make a wish, it will come true. This might be a new romantic place to discover."
# Place.create title: "Tulip Fields in Netherlands", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-2.jpg", content: "The weather in Holland is suited to tulip growing, with cool springs just as they begin to bloom. The soil in the polders is always being drained, making it perfect for tulip bulbs that like well-drained but moist soils. There are so many types of tulip varieties, that the Dutch Horticultural society has grouped them into several groups, with differing species within those groups. From mid-March to the end of May the tulips transform large parts of Holland into a colorful patchwork. So when you go to Holland in April to see the tulips bloom, no matter where you look, the fields will be different and no doubt gorgeously colorful."
# Place.create title: "Salar de Uyuni
# : One of the World’s Largest Mirrors, Bolivia", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-13-2.jpg", content: ""
# Place.create title: "Hitachi Seaside Park, Japan", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-23.jpg", content: ""
# Place.create title: "Mendenhall Ice Caves, Juneau, Alaska", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-1-1.jpg", content: ""
# Place.create title: "Red Beach, Panjin, China", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-24-2.jpg", content: ""
# Place.create title: "Bamboo Forest, Japan", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-3-1.jpg", content: ""
# Place.create title: "Street in Bonn, Germany", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-6.jpg", content: ""
# Place.create title: "Wisteria Flower Tunnel in Japan", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-7-1.jpg", content: ""
# Place.create title: "Black Forest, Germany", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-9.jpg", content: ""
# Place.create title: "Fields of Tea, China", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-11.jpg", content: ""
# Place.create title: "Tianzi Mountains, China", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-12-1.jpg", content: ""
# Place.create title: "Shibazakura Flowers, Takinoue Park, Japan", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-25-2.jpg", content: ""
# Place.create title: "Antelope Canyon, USA", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-15-2.jpg", content: ""
# Place.create title: "Lake Hillier, Australia", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-16.jpg", content: ""
# Place.create title: "Lake Retba, Senegal", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-27-1.jpg", content: ""
# Place.create title: "Lavender Fields, UK and France", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-10-1.jpg", content: ""
# Place.create title: "Canola Flower Fields, China", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-21-1.jpg", content: ""
# Place.create title: "Mount Roraima, Venezuela/Brazil/Guyana", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-19-1.jpg", content: ""
# Place.create title: "Zhangye Danxia Landform, China", photo: "http://static.boredpanda.com/blog/wp-content/uuuploads/unbelievable-places/unbelievable-places-27-3.jpg", content: ""
